.TH mumpot "1" "November 2008" "mumpot (mumpot 0.3.2)" "User Commands"
.SH NAME
mumpot, mumpot-tah, mumpot-mapnik. mumpot-cyclemap \- OSM map viewing, routing and editing program (mumpot 0.3.2)
.SH SYNOPSIS
.B mumpot
\fIconfigfile\fR
.br
.B mumpot-tah
.br
.B mumpot-mapnik
.br
.B mumpot-cyclemap
.SH DESCRIPTION
Mumpot is an OSM map viewing, routing and editing program
.PP
.B mumpot-tah,
.B mumpot-mapnik, mumpot-cyclemp
are wrappers around 
.B mumpot
which
can be called without parameters and select the corresponding map. 
If mumpot is called directly and no configuration file is given on
the command line,
mumpot searches in 
.B ~/.mumpot/map.conf
.br
If that file does not exists, a map selection dialog pops up
on startup.
One of these wrappers can be copied there and possibly, the line containing
.B filepattern
can be adjusted if the default storage locations for the tile cache
are not desireable.
.SH COPYRIGHT
Copyright \(co 2008 Andreas Kemnade
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License version 3 or any later version <http://www.gnu.org/licenses/gpl.html>
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
The full documentation is maintained in the README file. The web page http://www.mumpot.org/ is also a place to look at.
